name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          UPDATE_LABELS: "autorelease: pending"
          MERGE_LABELS: "autorelease: pending"
          MERGE_REMOVE_LABELS: "autorelease: pending"
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_RETRIES: "3"
          MERGE_RETRY_SLEEP: "2000"
          MERGE_ERROR_FAIL: "true"
          MERGE_METHOD: "merge"
          MERGE_FILTER_AUTHOR: "builder555"
          MERGE_FORKS: "false"
          LOG: "DEBUG"
